### ISSUE TITLE
{:error, :nxdomain} when using IPv6 domain name.

### ISSUE THREAD

**Issue by ghost** [Luminarys/Kaguya#1]
Numerous networks are now working with ipv6-only addressing, and it's a problem for Kaguya because there are no mechanisms to check if the address resolves to an ipv6 or ipv4 address. The user could specify it, or there could be an internal check, but in the end, `lib/core.ex:24` needs to look like `opts = [:binary, active: true, :inet6]`.

**Comment by Luminarys** [comment]
Sorry about the late response on this, I've gone ahead and implemented a fix in 8df1948944b105aacf1a6fb8bb477ab7ef90d3a5 with an explicit setting in the configuration for setting ipv4 or ipv6.
