### ISSUE TITLE
reconnect capabilities?

### ISSUE THREAD

**Issue by DoumanAsh** [Luminarys/Kaguya#12]
I would like check with you whether you implemented detection of connection loss to recover connection to server?
Noticed today when both my IRC client and my bot got disconnected, bot wasn't able to re-connect on its own.

**Comment by Luminarys** [comment]
In theory, if a connection is closed, the bot should attempt to reconnect, but I have not thoroughly tested this. You may want to trace what's happening in kaguya/core.ex, which is where all the socket handling occurs.

**Comment by DoumanAsh** [comment]
Yes, it seems it does nothing at all.
I remember seeing last PONG from bot and then there was nothing, while i already saw my bot get disconnected over server.

Once I'll finish writing up my bot I'll try to trace it

P.s. I suspect though that socket hasn't been closed and that's why it didn't try to re-connect. Still strange that server lost my bot

**Comment by DoumanAsh** [comment]
Left my bot for the whole night today... But fault still hasn't reproduced... :(
I'll try today too, if it would still not happen I suppose I'll close issue.

**Comment by Luminarys** [comment]
It might just be some odd TCP timeout edge case. If you can't find anything, I might try running Kaguya against some dummy IRC server which simulates timeouts and see if that turns anything up.

**Comment by DoumanAsh** [comment]
@Luminarys I discussed this scenario with some friends, it might be possible that server closes connection but Kaguya didn't receive RST for example. In this case you wouldn't know whether server alive or not based on TCP connection state.
Btw is it possible to find you maybe on some IRC channel so that we could discuss it directly?

**Comment by Luminarys** [comment]
feel free to PM me on Rizon/Freenode, my nick is luminarys on both.
