### ISSUE TITLE
No auto-rejoin to channels on reconnect

### ISSUE THREAD

**Issue by DoumanAsh** [Luminarys/Kaguya#17]
Finally reconnect happened to me and i noticed a thing that while Kaguya properly re-connects, your bot will not re-join channels that were joined on start.

I'll try to look into code more, but just letting you know.

**Comment by Luminarys** [comment]
Yea it doesn't surprise me, you'll probably want to look into the gproc registry used for channel processes and enable some sort of reconnect functionality. Thanks for the report!
