### ISSUE TITLE
Default help is provided when config doesn't containt hlp_cmd

### ISSUE THREAD

**Issue by DoumanAsh** [Luminarys/Kaguya#9]
I'm not sure if it is intended or not, but i noticed that if i omit `help_cmd` in config my bot gets `.help` command that basically prints:
```
[08:58:07] *Aru* .help Displays this message.
[08:58:07] *Aru* .help <search_term...> Displays all commands which match the supplied prefix.
```

Is it intended?
I would think that unless i specify, there should be no help command

**Comment by Luminarys** [comment]
This is probably a bug, I'll take a look.

**Comment by Luminarys** [comment]
What you're reporting is probably a result of not properly removing the help_cmd line from somewhere in your config(possibly the non secret file?). I've tested this and it appears to work correctly when help_cmd is not included.

**Comment by DoumanAsh** [comment]
Hm... that's strange as it is definitely defined only in one place.
Anyway sorry about false report.

**Comment by Luminarys** [comment]
You may want to try and force rebuild the project if you haven't, Application.get_env can be weird about some things being compiled in.
